"use client";

import { useState, useTransition } from "react";

import { Card, Button, Alert } from "@/components/ui";

import { createJoinCodeAction } from "./qr-actions";

/**
 * QR self-apply panel for admins. Shows the org's QR code + apply link (parents
 * scan it), or a button to create one. The SVG is rendered server-side and
 * passed in. Parents who scan land on /apply/[code], fill the form, verify their
 * email, and appear in the approval queue below.
 */
export function JoinCodePanel({
  hasCode,
  qrSvg,
  url,
}: {
  hasCode: boolean;
  qrSvg: string | null;
  url: string | null;
}) {
  const [pending, startTransition] = useTransition();
  const [error, setError] = useState<string | null>(null);
  const [copied, setCopied] = useState(false);

  function create() {
    setError(null);
    startTransition(async () => {
      const res = await createJoinCodeAction();
      if (!res.ok) setError(res.message);
    });
  }

  function copy() {
    if (!url) return;
    // Fire-and-forget; explicitly void the promise so the onClick handler stays
    // void-returning (and any rejection is swallowed deliberately).
    void (async () => {
      try {
        await navigator.clipboard.writeText(url);
        setCopied(true);
        setTimeout(() => setCopied(false), 1800);
      } catch {
        /* clipboard unavailable */
      }
    })();
  }

  return (
    <Card>
      <h2 className="text-sm font-medium text-zinc-700 dark:text-zinc-300">
        QR-Zugang
      </h2>
      <p className="mt-1 text-xs text-zinc-400">
        Häng diesen QR-Code am Aushang aus. Eltern scannen ihn, beantragen
        Zugang, und du gibst sie hier frei.
      </p>

      {hasCode && qrSvg ? (
        <div className="mt-3 flex flex-col items-center gap-3">
          <div
            className="rounded-xl bg-white p-3"
            // The SVG is generated by our own server (qrcode lib) from a trusted
            // URL — not user input — so rendering it inline is safe.
            dangerouslySetInnerHTML={{ __html: qrSvg }}
          />
          {url && (
            <div className="flex w-full gap-2">
              <input
                readOnly
                value={url}
                onFocus={(e) => e.currentTarget.select()}
                className="h-10 min-w-0 flex-1 rounded-lg border border-zinc-300 bg-zinc-50 px-3 text-xs text-zinc-700 dark:border-zinc-700 dark:bg-zinc-950 dark:text-zinc-300"
              />
              <button
                type="button"
                onClick={copy}
                className="shrink-0 rounded-lg border border-zinc-300 px-3 text-xs font-medium hover:bg-zinc-50 dark:border-zinc-700 dark:hover:bg-zinc-800"
              >
                {copied ? "Kopiert ✓" : "Link kopieren"}
              </button>
            </div>
          )}
        </div>
      ) : (
        <div className="mt-3">
          <Button onClick={create} disabled={pending}>
            {pending ? "Wird erstellt …" : "QR-Code erstellen"}
          </Button>
        </div>
      )}

      {error && (
        <div className="mt-2">
          <Alert variant="error">{error}</Alert>
        </div>
      )}
    </Card>
  );
}
