"use client";

import { useState, useTransition } from "react";

import { Card, Button, Alert, MiniButton } from "@/components/ui";
import { useT } from "@/lib/i18n/provider";

import { createJoinCodeAction } from "./qr-actions";

/**
 * QR self-apply panel for admins. Shows the org's QR code + apply link (parents
 * scan it), or a button to create one. The SVG is rendered server-side and
 * passed in. Parents who scan land on /apply/[code], fill the form, verify their
 * email, and appear in the approval queue below.
 */
export function JoinCodePanel({
  hasCode,
  qrSvg,
  url,
}: {
  hasCode: boolean;
  qrSvg: string | null;
  url: string | null;
}) {
  const t = useT();
  const [pending, startTransition] = useTransition();
  const [error, setError] = useState<string | null>(null);
  const [copied, setCopied] = useState(false);

  function create() {
    setError(null);
    startTransition(async () => {
      const res = await createJoinCodeAction();
      if (!res.ok) setError(res.message);
    });
  }

  function copy() {
    if (!url) return;
    // Fire-and-forget; explicitly void the promise so the onClick handler stays
    // void-returning (and any rejection is swallowed deliberately).
    void (async () => {
      try {
        await navigator.clipboard.writeText(url);
        setCopied(true);
        setTimeout(() => setCopied(false), 1800);
      } catch {
        /* clipboard unavailable */
      }
    })();
  }

  return (
    <Card>
      <h2 className="font-display text-base font-semibold text-ink">
        {t.members.qrHeading}
      </h2>
      <p className="mt-1 text-sm font-semibold text-ink-soft">
        {t.members.qrDesc}
      </p>

      {hasCode && qrSvg ? (
        <div className="mt-3 flex flex-col items-center gap-3">
          <div
            className="rounded-xl bg-white p-3"
            // The SVG is generated by our own server (qrcode lib) from a trusted
            // URL — not user input — so rendering it inline is safe.
            dangerouslySetInnerHTML={{ __html: qrSvg }}
          />
          {url && (
            <div className="flex w-full gap-2">
              <input
                readOnly
                value={url}
                onFocus={(e) => e.currentTarget.select()}
                className="h-11 min-w-0 flex-1 rounded-[12px] border border-border bg-white px-3 text-sm font-semibold text-ink-soft"
              />
              <MiniButton tone={copied ? "primary" : "neutral"} onClick={copy}>
                {copied ? t.common.copied : t.members.copyLink}
              </MiniButton>
            </div>
          )}
        </div>
      ) : (
        <div className="mt-3">
          <Button onClick={create} disabled={pending}>
            {pending ? t.members.qrCreating : t.members.qrCreate}
          </Button>
        </div>
      )}

      {error && (
        <div className="mt-2">
          <Alert variant="error">{error}</Alert>
        </div>
      )}
    </Card>
  );
}
