// Setup wizard — creates a LOCAL `.env.local` for a self-hosted copy of Aushang.
//
//   npm run setup
//
// SECURITY: this script only ever WRITES to YOUR OWN gitignored `.env.local`. It
// prompts for keys from YOUR OWN Supabase/Resend accounts — it does not (and
// cannot) access the maintainer's secrets, which live only in their deployment
// env and are never in this repo. The repo ships no secrets (a CI scan enforces
// that). Nothing you enter here is sent anywhere; it's written to a local file.
//
// What you need first (all free tiers):
//   1. A Supabase project in an EU region  -> Project URL + anon key + service-role key
//      (Supabase dashboard -> Project Settings -> API)
//   2. (optional) A Resend API key for invite/reset emails (resend.com)
//
// After this wizard: apply the SQL migrations (see README "Provision Supabase"),
// then `npm run dev`.

import { createInterface } from "node:readline/promises";
import { stdin, stdout } from "node:process";
import { writeFile, access } from "node:fs/promises";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = join(dirname(fileURLToPath(import.meta.url)), "..");
const ENV_PATH = join(ROOT, ".env.local");

const rl = createInterface({ input: stdin, output: stdout });

const C = {
  b: (s) => `\x1b[1m${s}\x1b[0m`,
  dim: (s) => `\x1b[2m${s}\x1b[0m`,
  green: (s) => `\x1b[32m${s}\x1b[0m`,
  yellow: (s) => `\x1b[33m${s}\x1b[0m`,
};

async function ask(label, { required = false, def = "", hint = "" } = {}) {
  const suffix = def ? C.dim(` [${def}]`) : "";
  for (;;) {
    if (hint) console.log(C.dim("  " + hint));
    const ans = (await rl.question(`${C.b(label)}${suffix}: `)).trim();
    const val = ans || def;
    if (!val && required) {
      console.log(C.yellow("  ↳ required — please enter a value."));
      continue;
    }
    return val;
  }
}

async function exists(p) {
  try {
    await access(p);
    return true;
  } catch {
    return false;
  }
}

function genVapid() {
  // web-push is a dependency already; generate a real VAPID keypair so push
  // works out of the box. If it isn't installed for some reason, skip gracefully.
  try {
    return import("web-push").then((m) => m.default.generateVAPIDKeys());
  } catch {
    return Promise.resolve(null);
  }
}

async function main() {
  console.log(C.b("\n  Aushang — local setup wizard\n"));
  console.log(
    C.dim(
      "  Writes a local .env.local with YOUR OWN keys. Nothing is sent anywhere.\n",
    ),
  );

  if (await exists(ENV_PATH)) {
    const ow = await ask(".env.local already exists — overwrite? (y/N)", {
      def: "N",
    });
    if (ow.toLowerCase() !== "y") {
      console.log(C.dim("  Aborted; left your .env.local untouched.\n"));
      rl.close();
      return;
    }
  }

  console.log(
    C.b("\n  1) Supabase") + C.dim("  (dashboard → Settings → API)\n"),
  );
  const supabaseUrl = await ask("Supabase Project URL", {
    required: true,
    hint: "e.g. https://abcd1234.supabase.co (use an EU region project)",
  });
  const anonKey = await ask("Supabase anon (publishable) key", {
    required: true,
    hint: "public by design — RLS protects the data",
  });
  const serviceKey = await ask("Supabase service-role key", {
    required: true,
    hint: "SERVER-ONLY master key — bypasses RLS. Stored only in your .env.local.",
  });

  console.log(C.b("\n  2) Site\n"));
  const siteUrl = await ask("Site URL", {
    def: "http://localhost:3000",
    hint: "scheme + host, no trailing slash",
  });

  console.log(C.b("\n  3) Operator (you)\n"));
  const superadmin = await ask(
    "Your email (becomes the operator on first login)",
    {
      hint: "comma-separated for multiple; auto-elevated to superadmin",
    },
  );

  console.log(C.b("\n  4) Email — optional") + C.dim("  (resend.com)\n"));
  const resendKey = await ask("Resend API key", {
    hint: "leave blank to skip — invite/reset emails just won't send",
  });
  const emailFrom = resendKey
    ? await ask("Email FROM address", {
        def: "Aushang <onboarding@resend.dev>",
        hint: "use a Resend-verified domain in production",
      })
    : "";

  console.log(C.dim("\n  Generating a Web Push (VAPID) keypair…"));
  const vapid = await genVapid();

  const lines = [
    "# Generated by `npm run setup`. Gitignored — never commit this file.",
    "",
    `NEXT_PUBLIC_SUPABASE_URL="${supabaseUrl}"`,
    `NEXT_PUBLIC_SUPABASE_ANON_KEY="${anonKey}"`,
    `NEXT_PUBLIC_SITE_URL="${siteUrl}"`,
    "",
    `SUPABASE_SERVICE_ROLE_KEY="${serviceKey}"`,
    `SUPERADMIN_EMAILS="${superadmin}"`,
    "",
    `RESEND_API_KEY="${resendKey}"`,
    `EMAIL_FROM="${emailFrom}"`,
    "",
    "# Worker (OCR/redaction/LLM) — set these once you deploy the Python worker.",
    'WORKER_URL=""',
    'WORKER_SHARED_SECRET=""',
    "",
  ];
  if (vapid) {
    lines.push(
      `NEXT_PUBLIC_VAPID_PUBLIC_KEY="${vapid.publicKey}"`,
      `VAPID_PRIVATE_KEY="${vapid.privateKey}"`,
      `VAPID_SUBJECT="mailto:${(superadmin || "you@example.com").split(",")[0].trim()}"`,
      "",
    );
  }

  await writeFile(ENV_PATH, lines.join("\n"), { mode: 0o600 });

  console.log(C.green("\n  ✓ Wrote .env.local") + C.dim(" (chmod 600)\n"));
  console.log(C.b("  Next steps:"));
  console.log(
    "   1. Apply the SQL migrations in supabase/migrations/ in order\n" +
      "      (Supabase SQL editor or `supabase db push`). See README.",
  );
  console.log(
    "   2. In Supabase → Auth: enable Email provider with password sign-in ON,\n" +
      "      and set 'Allow new users to sign up' = OFF (invite-only).",
  );
  console.log("   3. npm run dev   →   http://localhost:3000");
  console.log(
    "   4. Log in with your operator email (use 'Passwort vergessen' to set a\n" +
      "      first password). You'll be elevated to operator on first login.\n",
  );
  console.log(
    C.dim(
      "  The OCR/redaction worker (worker/) is optional — without it, captured\n" +
        "  photos upload but stay 'processing'. The rest of the app works.\n",
    ),
  );

  rl.close();
}

main().catch((err) => {
  console.error("setup failed:", err);
  rl.close();
  process.exit(1);
});
